Added code to register,delete and list services to monitor

diff --git a/bin/gesapl b/bin/gesapl
--- a/bin/gesapl
+++ b/bin/gesapl
@@ -1,27 +1,167 @@
 #!/bin/bash
 
+# TODO
+# - Poner el nombre de las variables en inglés
+
 # Configuration section
 CONFIG_FILE="/home/theangryjose/Software/gesapl/etc/gesapl/gesapl.conf"
+GESAPL_VERSION="1.00"
 
 # Functions
 function help {
-    printf "%s\n"  "GesApl v1.00 - Aplicación de monitorización de servicios"
+    printf "%s\n"  "GesApl v${GESAPL_VERSION} - Aplicación de monitorización de servicios"
+
+    printf "\nUso: gesapl orden parámetros
+
+Siendo orden una de las siguientes: --registrar_servicio (o -rs), --borrar_servicio (o -bs), --ayuda (o -a)
+
+    -rs | --registrar_servicio nombre script_de_arranque ruta_fichero_pid proceso :  Registra un servicio e inicia su monitorización
+
+        El nombre de servicio es arbitrario, es el nombre con el que gesapl lo va a tratar
+        El script de arranque es el nombre del script de arranque/parada en /etc/init.d
+        El proceso es el nombre del proceso con el que se le ve en el sistema
+
+    -bs | --borrar_servicio nombre :  Borra el servicio indicado
+
+    -ls | --listar_servicios :  Lista los servicios monitorizados y los parámetros registrados para cada uno
+
+    -a | --ayuda :  Muestra este mensaje explicativo
+
+Ejemplos: 
+
+Monitorizar Apache y MySQL
+    gesapl --registrar_servicio apache apache2 /var/run/apache2/apache2.pid /usr/sbin/apache2
+    gesapl --registrar_servicio mysql mysql /run/mysqld/mysql.pid /usr/sbin/mysqld
+
+Dejar de monitorizar MySQL
+    gesapl --borrar_servicio mysql
+
+"
 }
 
 
 
 # Main
 if ! [ -r ${CONFIG_FILE} ];  then
-    printf "ERROR: %s!\n\n" "Configuration file ${CONFIG_FILE} not found or not readable"
-
+    printf "ERROR: %s!\n\n" "Fichero de configuración ${CONFIG_FILE} no encontrado o imposible de leer"
     help
-
-    printf "\n"
     exit 1
 fi;
 
 source ${CONFIG_FILE}
 
+# Default values
+comando=""
 
-help
+# Parse arguments
+if [[ $# -eq 0 ]]; then
+    printf "ERROR %s\n\n" "Número de parámetros incorrecto"
+    help
+    exit 1
+fi;
+
+case $1 in
+    -rs|--registrar_servicio)
+        comando="rs"
+        shift
+        nombre=$1
+        shift
+        script_arranque=$1
+        shift
+        fichero_pid=$1
+        shift
+        proceso=$1
+        shift
+
+        if [ -z "${nombre}" -o -z "${script_arranque}" -o -z "${fichero_pid}" -o -z "${proceso}" ]; then
+            printf "ERROR %s\n\n" "Número de parámetros incorrecto"
+            help
+            exit 1
+        fi
+        ;;
+    -bs|--borrar_servicio)
+        comando="bs"
+        shift
+        nombre=$1
+        shift
+
+        if [ -z "${nombre}" -o $# -ne 0  ]; then
+            printf "ERROR %s\n\n" "Número de parámetros incorrecto"
+            help
+            exit 1
+        fi
+        ;;
+    -ls|--listar_servicios)
+        comando="ls"
+        shift
+        ;;
+    -a|--ayuda)
+        help
+        ;;
+    *)
+        printf "ERROR %s\n\n" "Orden no reconocida"
+        help
+        exit 1
+        ;;
+esac;
+
+case ${comando} in
+    rs)
+        if ! [[ -d "${services_data}" ]]; then
+            mkdir -p "${services_data}"
+            rc=$?
+            if [[ ${rc} -ne 0 ]]; then
+                printf "ERROR: %s\n\n" "Error al crear el directorio ${services_data}"
+                exit 1
+            fi;
+        fi;
+
+        if [ -f "${services_data}/${nombre}" ]; then
+            printf "ERROR: %s\n\n" "El servicio ${nombre} ya ha sido registrado en gesappl"
+            exit 1
+        fi;
+
+        echo "${script_arranque},${fichero_pid},${proceso}" > "${services_data}/${nombre}"
+        rc=$?
+        if [[ ${rc} -ne 0 ]]; then
+            printf "ERROR: %s\n\n" "Error al añadir el servicio ${nombre}"
+            exit 1
+        fi;
+
+        printf "Añadida la monitorización del servicio ${nombre}\n\n"
+        ;;
+    bs)
+        if ! [ -f "${services_data}/${nombre}" ]; then
+            printf "ERROR: %s\n\n" "El servicio ${nombre} no está siendo monitorizado por gesappl"
+            exit 1
+        fi;
+        mv "${services_data}/${nombre}" "${services_data}/${nombre}_stopped"
+        rc=$?
+        if [[ ${rc} -ne 0 ]]; then
+            printf "ERROR: %s\n\n" "Error al eliminar el servicio ${nombre}"
+            exit 1
+        fi;
+
+        printf "Detenida la monitorización del servicio ${nombre}\n\n"
+        ;;
+    ls)
+        printf "%s\n"  "GesApl v${GESAPL_VERSION} - Aplicación de monitorización de servicios"
+        services_info_files="$(find "${services_data}" -type f|grep -v '_stopped$'|sort)"
+
+        if [[ -n "${services_info_files}" ]]; then
+            printf "\nServicios monitorizados:\n"
+            for f in ${services_info_files}; do
+                service_info="$(cat ${f})"
+                script_arranque="$(echo ${service_info}|cut -f1 -d',')"
+                fichero_pid="$(echo ${service_info}|cut -f2 -d',')"
+                proceso="$(echo ${service_info}|cut -f3 -d',')"
+                printf "\t- %s :  script de arranque=/etc/init.d/%s, fichero pid=%s, proceso=%s\n" ${f##*/} ${script_arranque} ${fichero_pid} ${proceso}
+            done;
+        else
+            printf "Ningún servicio está siendo monitorizado por gesapl"
+        fi;
+        ;;
+
+esac
+
 
